# Generated by Django 5.1.4 on 2025-01-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_chatroom_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
