# Generated by Django 5.1.4 on 2025-01-22 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_chatroom_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Chat Message', 'verbose_name_plural': 'Chat Messages'},
        ),
    ]
