# Generated by Django 5.1.4 on 2025-02-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_chatmessage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('dm', 'Direct Message'), ('group', 'Group Chat')], default='dm', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
