# Generated by Django 5.1.4 on 2025-03-04 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='chat_files/%Y/%m/%d/')),
                ('name', models.CharField(max_length=255)),
                ('size', models.BigIntegerField()),
                ('content_type', models.CharField(max_length=100, null=True)),
                ('chat_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='user.chatmessage')),
            ],
        ),
    ]
